'''
Created on Apr 8, 2021

@author: bleem
'''

SCHEDULE_TYPE_VI = "VI"
SCHEDULE_TYPE_VR = "VR"
SCHEDULE_TYPE_DVI = "DVI"

# enumeration of net types
NET_TYPE_ONE = 1
NET_TYPE_TWO = 2
NET_TYPE_ETBD = 3
NET_TYPE_NULL_MARKOV = 0
NET_TYPE_NULL_Q = -1

POLICY_TYPE_MAX = 1
POLICY_TYPE_EPSILON_GREEDY = 2
POLICY_TYPE_BOLTZMANN = 3
POLICY_TYPE_HYPERBOLIC = 4
POLICY_TYPE_LINEAR = 5
POLICY_TYPE_QUADRATIC = 6
POLICY_TYPE_EPSILON_BOLTZMANN = 7

# default values
DEFAULT_FDF = 40
